import { convertTheme } from "monaco-vscode-textmate-theme-converter"; // UMD module
import fs from "fs";
// import { convertTheme, convertThemeFromDir } from 'monaco-vscode-textmate-theme-converter/lib/cjs'; // cjs module

/*
 * In vscode use command: `Developer: Generate Color Theme From Current Settings`
 * Copy the generated JSON and use it as input for the function below.
 */
const theme = {
  $schema: "vscode://schemas/color-theme",
  type: "dark",
  colors: {
    "activityBar.activeBorder": "#80cbc4",
    "activityBar.background": "#1b1e2b",
    "activityBar.border": "#00000060",
    "activityBar.foreground": "#a6accd",
    "activityBarBadge.background": "#80cbc4",
    "activityBarBadge.foreground": "#000000",
    "badge.background": "#00000030",
    "badge.foreground": "#676e95",
    "breadcrumb.activeSelectionForeground": "#80cbc4",
    "breadcrumb.background": "#292d3e",
    "breadcrumb.focusForeground": "#a6accd",
    "breadcrumb.foreground": "#757ca1",
    "breadcrumbPicker.background": "#1b1e2b",
    "button.background": "#717cb450",
    "button.foreground": "#ffffff",
    "debugConsole.errorForeground": "#f07178",
    "debugConsole.infoForeground": "#89ddff",
    "debugConsole.warningForeground": "#ffcb6b",
    "debugToolBar.background": "#292d3e",
    "diffEditor.insertedTextBackground": "#89ddff20",
    "diffEditor.removedTextBackground": "#ff9cac20",
    "dropdown.background": "#292d3e",
    "dropdown.border": "#ffffff10",
    "editor.background": "#292d3e",
    "editor.findMatchBackground": "#000000",
    "editor.findMatchBorder": "#80cbc4",
    "editor.findMatchHighlightBackground": "#00000050",
    "editor.findMatchHighlightBorder": "#ffffff50",
    "editor.findRangeHighlightBackground": "#ffcb6b30",
    "editor.foreground": "#a6accd",
    "editor.lineHighlightBackground": "#00000050",
    "editor.lineHighlightBorder": "#00000000",
    "editor.rangeHighlightBackground": "#ffffff0d",
    "editor.selectionBackground": "#717cb450",
    "editor.selectionHighlightBackground": "#ffcc0020",
    "editor.wordHighlightBackground": "#ff9cac30",
    "editor.wordHighlightStrongBackground": "#c3e88d30",
    "editorBracketMatch.background": "#292d3e",
    "editorBracketMatch.border": "#ffcc0050",
    "editorCursor.foreground": "#ffcc00",
    "editorError.foreground": "#f0717870",
    "editorGroup.border": "#00000030",
    "editorGroup.dropBackground": "#f0717880",
    "editorGroup.focusedEmptyBorder": "#f07178",
    "editorGroupHeader.tabsBackground": "#292d3e",
    "editorGutter.addedBackground": "#c3e88d60",
    "editorGutter.deletedBackground": "#f0717860",
    "editorGutter.modifiedBackground": "#82aaff60",
    "editorHoverWidget.background": "#292d3e",
    "editorHoverWidget.border": "#ffffff10",
    "editorIndentGuide.activeBackground": "#4e5579",
    "editorIndentGuide.background": "#4e557970",
    "editorInfo.foreground": "#82aaff70",
    "editorLineNumber.activeForeground": "#757ca1",
    "editorLineNumber.foreground": "#3a3f58",
    "editorLink.activeForeground": "#a6accd",
    "editorMarkerNavigation.background": "#a6accd05",
    "editorOverviewRuler.border": "#292d3e",
    "editorOverviewRuler.errorForeground": "#f0717840",
    "editorOverviewRuler.findMatchForeground": "#80cbc4",
    "editorOverviewRuler.infoForeground": "#82aaff40",
    "editorOverviewRuler.warningForeground": "#ffcb6b40",
    "editorRuler.foreground": "#4e5579",
    "editorSuggestWidget.background": "#292d3e",
    "editorSuggestWidget.border": "#ffffff10",
    "editorSuggestWidget.foreground": "#a6accd",
    "editorSuggestWidget.highlightForeground": "#80cbc4",
    "editorSuggestWidget.selectedBackground": "#00000050",
    "editorWarning.foreground": "#ffcb6b70",
    "editorWhitespace.foreground": "#a6accd40",
    "editorWidget.background": "#1b1e2b",
    "editorWidget.border": "#80cbc4",
    "editorWidget.resizeBorder": "#80cbc4",
    "extensionBadge.remoteForeground": "#a6accd",
    "extensionButton.prominentBackground": "#c3e88d90",
    "extensionButton.prominentForeground": "#000000",
    "extensionButton.prominentHoverBackground": "#c3e88d",
    focusBorder: "#ffffff00",
    foreground: "#a6accd",
    "gitDecoration.conflictingResourceForeground": "#ffcb6b90",
    "gitDecoration.deletedResourceForeground": "#f0717890",
    "gitDecoration.ignoredResourceForeground": "#757ca190",
    "gitDecoration.modifiedResourceForeground": "#82aaff90",
    "gitDecoration.untrackedResourceForeground": "#c3e88d90",
    "input.background": "#333747",
    "input.border": "#ffffff10",
    "input.foreground": "#a6accd",
    "input.placeholderForeground": "#a6accd60",
    "inputOption.activeBackground": "#a6accd30",
    "inputOption.activeBorder": "#a6accd30",
    "inputValidation.errorBorder": "#f07178",
    "inputValidation.infoBorder": "#82aaff",
    "inputValidation.warningBorder": "#ffcb6b",
    "list.activeSelectionBackground": "#1b1e2b",
    "list.activeSelectionForeground": "#80cbc4",
    "list.dropBackground": "#f0717880",
    "list.focusBackground": "#a6accd20",
    "list.focusForeground": "#a6accd",
    "list.highlightForeground": "#80cbc4",
    "list.hoverBackground": "#1b1e2b",
    "list.hoverForeground": "#ffffff",
    "list.inactiveSelectionBackground": "#00000030",
    "list.inactiveSelectionForeground": "#80cbc4",
    "listFilterWidget.background": "#00000030",
    "listFilterWidget.noMatchesOutline": "#00000030",
    "listFilterWidget.outline": "#00000030",
    "menu.background": "#292d3e",
    "menu.foreground": "#a6accd",
    "menu.selectionBackground": "#00000050",
    "menu.selectionBorder": "#00000030",
    "menu.selectionForeground": "#80cbc4",
    "menu.separatorBackground": "#a6accd",
    "menubar.selectionBackground": "#00000030",
    "menubar.selectionBorder": "#00000030",
    "menubar.selectionForeground": "#80cbc4",
    "notebook.focusedCellBorder": "#80cbc4",
    "notebook.inactiveFocusedCellBorder": "#80cbc450",
    "notificationLink.foreground": "#80cbc4",
    "notifications.background": "#292d3e",
    "notifications.foreground": "#a6accd",
    "panel.background": "#1b1e2b",
    "panel.border": "#00000060",
    "panelTitle.activeBorder": "#80cbc4",
    "panelTitle.activeForeground": "#ffffff",
    "panelTitle.inactiveForeground": "#a6accd",
    "peekView.border": "#00000030",
    "peekViewEditor.background": "#a6accd05",
    "peekViewEditor.matchHighlightBackground": "#717cb450",
    "peekViewEditorGutter.background": "#a6accd05",
    "peekViewResult.background": "#a6accd05",
    "peekViewResult.matchHighlightBackground": "#717cb450",
    "peekViewResult.selectionBackground": "#757ca170",
    "peekViewTitle.background": "#a6accd05",
    "peekViewTitleDescription.foreground": "#a6accd60",
    "pickerGroup.border": "#ffffff1a",
    "pickerGroup.foreground": "#80cbc4",
    "progressBar.background": "#80cbc4",
    "quickInput.background": "#292d3e",
    "quickInput.foreground": "#757ca1",
    "quickInput.list.focusBackground": "#a6accd20",
    "scrollbar.shadow": "#00000030",
    "scrollbarSlider.activeBackground": "#80cbc4",
    "scrollbarSlider.background": "#a6accd20",
    "scrollbarSlider.hoverBackground": "#a6accd10",
    "selection.background": "#00000080",
    "settings.checkboxBackground": "#1b1e2b",
    "settings.checkboxForeground": "#a6accd",
    "settings.dropdownBackground": "#1b1e2b",
    "settings.dropdownForeground": "#a6accd",
    "settings.headerForeground": "#80cbc4",
    "settings.modifiedItemIndicator": "#80cbc4",
    "settings.numberInputBackground": "#1b1e2b",
    "settings.numberInputForeground": "#a6accd",
    "settings.textInputBackground": "#1b1e2b",
    "settings.textInputForeground": "#a6accd",
    "sideBar.background": "#1b1e2b",
    "sideBar.border": "#00000060",
    "sideBar.foreground": "#757ca1",
    "sideBarSectionHeader.background": "#1b1e2b",
    "sideBarSectionHeader.border": "#00000060",
    "sideBarTitle.foreground": "#a6accd",
    "statusBar.background": "#1b1e2b",
    "statusBar.border": "#00000060",
    "statusBar.debuggingBackground": "#c792ea",
    "statusBar.debuggingForeground": "#ffffff",
    "statusBar.foreground": "#676e95",
    "statusBar.noFolderBackground": "#292d3e",
    "statusBarItem.activeBackground": "#f0717880",
    "statusBarItem.hoverBackground": "#676e9520",
    "statusBarItem.remoteBackground": "#80cbc4",
    "statusBarItem.remoteForeground": "#000000",
    "tab.activeBackground": "#292d3e",
    "tab.activeBorder": "#80cbc4",
    "tab.activeForeground": "#ffffff",
    "tab.activeModifiedBorder": "#757ca1",
    "tab.border": "#292d3e",
    "tab.inactiveBackground": "#292d3e",
    "tab.inactiveForeground": "#757ca1",
    "tab.inactiveModifiedBorder": "#904348",
    "tab.unfocusedActiveBorder": "#676e95",
    "tab.unfocusedActiveForeground": "#a6accd",
    "tab.unfocusedActiveModifiedBorder": "#c05a60",
    "tab.unfocusedInactiveModifiedBorder": "#904348",
    "terminal.ansiBlack": "#000000",
    "terminal.ansiBlue": "#82aaff",
    "terminal.ansiBrightBlack": "#676e95",
    "terminal.ansiBrightBlue": "#82aaff",
    "terminal.ansiBrightCyan": "#89ddff",
    "terminal.ansiBrightGreen": "#c3e88d",
    "terminal.ansiBrightMagenta": "#c792ea",
    "terminal.ansiBrightRed": "#f07178",
    "terminal.ansiBrightWhite": "#ffffff",
    "terminal.ansiBrightYellow": "#ffcb6b",
    "terminal.ansiCyan": "#89ddff",
    "terminal.ansiGreen": "#c3e88d",
    "terminal.ansiMagenta": "#c792ea",
    "terminal.ansiRed": "#f07178",
    "terminal.ansiWhite": "#ffffff",
    "terminal.ansiYellow": "#ffcb6b",
    "terminalCursor.background": "#000000",
    "terminalCursor.foreground": "#ffcb6b",
    "textLink.activeForeground": "#a6accd",
    "textLink.foreground": "#80cbc4",
    "titleBar.activeBackground": "#1b1e2b",
    "titleBar.activeForeground": "#a6accd",
    "titleBar.border": "#00000060",
    "titleBar.inactiveBackground": "#1b1e2b",
    "titleBar.inactiveForeground": "#757ca1",
    "tree.indentGuidesStroke": "#4e5579",
    "widget.shadow": "#00000030",
    //"activityBar.dropBorder": "#a6accd",
    //"activityBar.inactiveForeground": "#a6accd66",
    //"banner.background": "#1b1e2b",
    //"banner.foreground": "#80cbc4",
    //"banner.iconForeground": "#82aaff70",
    //"button.hoverBackground": "#98a0c850",
    //"button.secondaryBackground": "#3a3d41",
    //"button.secondaryForeground": "#ffffff",
    //"button.secondaryHoverBackground": "#45494e",
    //"button.separator": "#ffffff66",
    //"charts.blue": "#82aaff70",
    //"charts.foreground": "#a6accd",
    //"charts.green": "#89d185",
    //"charts.lines": "#a6accd80",
    //"charts.orange": "#d18616",
    //"charts.purple": "#b180d7",
    //"charts.red": "#f0717870",
    //"charts.yellow": "#ffcb6b70",
    //"checkbox.background": "#292d3e",
    //"checkbox.border": "#ffffff10",
    //"checkbox.foreground": "#f0f0f0",
    //"checkbox.selectBackground": "#1b1e2b",
    //"checkbox.selectBorder": "#c5c5c5",
    //"commandCenter.activeBackground": "#ffffff14",
    //"commandCenter.activeBorder": "#a6accd4d",
    //"commandCenter.activeForeground": "#80cbc4",
    //"commandCenter.background": "#ffffff0d",
    //"commandCenter.border": "#a6accd33",
    //"commandCenter.foreground": "#a6accd",
    //"commandCenter.inactiveBorder": "#757ca140",
    //"commandCenter.inactiveForeground": "#757ca1",
    //"debugConsole.sourceForeground": "#a6accd",
    //"debugConsoleInputIcon.foreground": "#a6accd",
    //"debugExceptionWidget.background": "#420b0d",
    //"debugExceptionWidget.border": "#a31515",
    //"debugIcon.breakpointCurrentStackframeForeground": "#ffcc00",
    //"debugIcon.breakpointDisabledForeground": "#848484",
    //"debugIcon.breakpointForeground": "#e51400",
    //"debugIcon.breakpointStackframeForeground": "#89d185",
    //"debugIcon.breakpointUnverifiedForeground": "#848484",
    //"debugIcon.continueForeground": "#75beff",
    //"debugIcon.disconnectForeground": "#f48771",
    //"debugIcon.pauseForeground": "#75beff",
    //"debugIcon.restartForeground": "#89d185",
    //"debugIcon.startForeground": "#89d185",
    //"debugIcon.stepBackForeground": "#75beff",
    //"debugIcon.stepIntoForeground": "#75beff",
    //"debugIcon.stepOutForeground": "#75beff",
    //"debugIcon.stepOverForeground": "#75beff",
    //"debugIcon.stopForeground": "#f48771",
    //"debugTokenExpression.boolean": "#4e94ce",
    //"debugTokenExpression.error": "#f48771",
    //"debugTokenExpression.name": "#c586c0",
    //"debugTokenExpression.number": "#b5cea8",
    //"debugTokenExpression.string": "#ce9178",
    //"debugTokenExpression.value": "#cccccc99",
    //"debugView.exceptionLabelBackground": "#6c2022",
    //"debugView.exceptionLabelForeground": "#a6accd",
    //"debugView.stateLabelBackground": "#88888844",
    //"debugView.stateLabelForeground": "#a6accd",
    //"debugView.valueChangedHighlight": "#569cd6",
    //"descriptionForeground": "#a6accdb3",
    //"diffEditor.diagonalFill": "#cccccc33",
    //"diffEditor.insertedLineBackground": "#9bb95533",
    //"diffEditor.removedLineBackground": "#ff000033",
    //"disabledForeground": "#cccccc80",
    //"dropdown.foreground": "#f0f0f0",
    //"editor.focusedStackFrameHighlightBackground": "#7abd7a4d",
    //"editor.foldBackground": "#717cb418",
    //"editor.hoverHighlightBackground": "#264f7840",
    //"editor.inactiveSelectionBackground": "#717cb428",
    //"editor.inlineValuesBackground": "#ffc80033",
    //"editor.inlineValuesForeground": "#ffffff80",
    //"editor.linkedEditingBackground": "#ff00004d",
    //"editor.snippetFinalTabstopHighlightBorder": "#525252",
    //"editor.snippetTabstopHighlightBackground": "#7c7c7c4d",
    //"editor.stackFrameHighlightBackground": "#ffff0033",
    //"editor.symbolHighlightBackground": "#00000050",
    //"editor.wordHighlightTextBackground": "#ff9cac30",
    //"editorActiveLineNumber.foreground": "#c6c6c6",
    //"editorBracketHighlight.foreground1": "#ffd700",
    //"editorBracketHighlight.foreground2": "#da70d6",
    //"editorBracketHighlight.foreground3": "#179fff",
    //"editorBracketHighlight.foreground4": "#00000000",
    //"editorBracketHighlight.foreground5": "#00000000",
    //"editorBracketHighlight.foreground6": "#00000000",
    //"editorBracketHighlight.unexpectedBracket.foreground": "#ff1212cc",
    //"editorBracketPairGuide.activeBackground1": "#00000000",
    //"editorBracketPairGuide.activeBackground2": "#00000000",
    //"editorBracketPairGuide.activeBackground3": "#00000000",
    //"editorBracketPairGuide.activeBackground4": "#00000000",
    //"editorBracketPairGuide.activeBackground5": "#00000000",
    //"editorBracketPairGuide.activeBackground6": "#00000000",
    //"editorBracketPairGuide.background1": "#00000000",
    //"editorBracketPairGuide.background2": "#00000000",
    //"editorBracketPairGuide.background3": "#00000000",
    //"editorBracketPairGuide.background4": "#00000000",
    //"editorBracketPairGuide.background5": "#00000000",
    //"editorBracketPairGuide.background6": "#00000000",
    //"editorCodeLens.foreground": "#999999",
    //"editorCommentsWidget.rangeActiveBackground": "#00000005",
    //"editorCommentsWidget.rangeActiveBorder": "#00000013",
    //"editorCommentsWidget.rangeBackground": "#00000005",
    //"editorCommentsWidget.rangeBorder": "#00000013",
    //"editorCommentsWidget.resolvedBorder": "#cccccc80",
    //"editorCommentsWidget.unresolvedBorder": "#00000030",
    //"editorGhostText.foreground": "#ffffff56",
    //"editorGroup.dropIntoPromptBackground": "#1b1e2b",
    //"editorGroup.dropIntoPromptForeground": "#a6accd",
    //"editorGroupHeader.noTabsBackground": "#292d3e",
    //"editorGutter.background": "#292d3e",
    //"editorGutter.commentGlyphForeground": "#a6accd",
    //"editorGutter.commentRangeForeground": "#212432",
    //"editorGutter.commentUnresolvedGlyphForeground": "#a6accd",
    //"editorGutter.foldingControlForeground": "#c5c5c5",
    //"editorHint.foreground": "#eeeeeeb3",
    //"editorHoverWidget.foreground": "#a6accd",
    //"editorHoverWidget.highlightForeground": "#80cbc4",
    //"editorHoverWidget.statusBarBackground": "#31364a",
    //"editorInlayHint.background": "#00000026",
    //"editorInlayHint.foreground": "#676e95",
    //"editorInlayHint.parameterBackground": "#00000026",
    //"editorInlayHint.parameterForeground": "#676e95",
    //"editorInlayHint.typeBackground": "#00000026",
    //"editorInlayHint.typeForeground": "#676e95",
    //"editorLightBulb.foreground": "#ffcc00",
    //"editorLightBulbAutoFix.foreground": "#75beff",
    //"editorMarkerNavigationError.background": "#f0717870",
    //"editorMarkerNavigationError.headerBackground": "#f071780b",
    //"editorMarkerNavigationInfo.background": "#82aaff70",
    //"editorMarkerNavigationInfo.headerBackground": "#82aaff0b",
    //"editorMarkerNavigationWarning.background": "#ffcb6b70",
    //"editorMarkerNavigationWarning.headerBackground": "#ffcb6b0b",
    //"editorOverviewRuler.addedForeground": "#c3e88d3a",
    //"editorOverviewRuler.bracketMatchForeground": "#a0a0a0",
    //"editorOverviewRuler.commonContentForeground": "#60606066",
    //"editorOverviewRuler.currentContentForeground": "#40c8ae80",
    //"editorOverviewRuler.deletedForeground": "#f071783a",
    //"editorOverviewRuler.incomingContentForeground": "#40a6ff80",
    //"editorOverviewRuler.modifiedForeground": "#82aaff3a",
    //"editorOverviewRuler.rangeHighlightForeground": "#007acc99",
    //"editorOverviewRuler.selectionHighlightForeground": "#a0a0a0cc",
    //"editorOverviewRuler.wordHighlightForeground": "#a0a0a0cc",
    //"editorOverviewRuler.wordHighlightStrongForeground": "#c0a0c0cc",
    //"editorOverviewRuler.wordHighlightTextForeground": "#a0a0a0cc",
    //"editorPane.background": "#292d3e",
    //"editorStickyScroll.background": "#292d3e",
    //"editorStickyScrollHover.background": "#2a2d2e",
    //"editorSuggestWidget.focusHighlightForeground": "#80cbc4",
    //"editorSuggestWidget.selectedForeground": "#80cbc4",
    //"editorSuggestWidgetStatus.foreground": "#a6accd80",
    //"editorUnicodeHighlight.background": "#bd9b0326",
    //"editorUnicodeHighlight.border": "#bd9b03",
    //"editorUnnecessaryCode.opacity": "#000000aa",
    //"editorWidget.foreground": "#a6accd",
    //"errorForeground": "#f48771",
    //"extensionBadge.remoteBackground": "#80cbc4",
    //"extensionButton.background": "#717cb450",
    //"extensionButton.foreground": "#ffffff",
    //"extensionButton.hoverBackground": "#98a0c850",
    //"extensionButton.separator": "#ffffff66",
    //"extensionIcon.preReleaseForeground": "#1d9271",
    //"extensionIcon.sponsorForeground": "#d758b3",
    //"extensionIcon.starForeground": "#ff8e00",
    //"extensionIcon.verifiedForeground": "#80cbc4",
    //"gitDecoration.addedResourceForeground": "#81b88b",
    //"gitDecoration.renamedResourceForeground": "#73c991",
    //"gitDecoration.stageDeletedResourceForeground": "#c74e39",
    //"gitDecoration.stageModifiedResourceForeground": "#e2c08d",
    //"gitDecoration.submoduleResourceForeground": "#8db9e2",
    //"icon.foreground": "#c5c5c5",
    //"inputOption.activeForeground": "#ffffff",
    //"inputOption.hoverBackground": "#5a5d5e80",
    //"inputValidation.errorBackground": "#5a1d1d",
    //"inputValidation.infoBackground": "#063b49",
    //"inputValidation.warningBackground": "#352a05",
    //"interactive.activeCodeBorder": "#00000030",
    //"interactive.inactiveCodeBorder": "#00000030",
    //"interactive.requestBackground": "#ffffff08",
    //"interactive.requestBorder": "#ffffff1a",
    //"interactiveEditor.border": "#80cbc4",
    //"interactiveEditor.regionHighlight": "#264f7840",
    //"interactiveEditor.shadow": "#00000030",
    //"interactiveEditorDiff.inserted": "#89ddff10",
    //"interactiveEditorDiff.removed": "#ff9cac10",
    //"interactiveEditorInput.background": "#333747",
    //"interactiveEditorInput.border": "#80cbc4",
    //"interactiveEditorInput.focusBorder": "#ffffff00",
    //"interactiveEditorInput.placeholderForeground": "#a6accd60",
    //"keybindingLabel.background": "#8080802b",
    //"keybindingLabel.border": "#33333399",
    //"keybindingLabel.bottomBorder": "#44444499",
    //"keybindingLabel.foreground": "#cccccc",
    //"keybindingTable.headerBackground": "#a6accd0a",
    //"keybindingTable.rowsBackground": "#a6accd0a",
    //"list.deemphasizedForeground": "#8c8c8c",
    //"list.errorForeground": "#f88070",
    //"list.filterMatchBackground": "#00000050",
    //"list.filterMatchBorder": "#ffffff50",
    //"list.focusHighlightForeground": "#80cbc4",
    //"list.focusOutline": "#ffffff00",
    //"list.invalidItemForeground": "#b89500",
    //"list.warningForeground": "#cca700",
    //"listFilterWidget.shadow": "#00000030",
    //"markdown.extension.editor.codeSpan.background": "#00000000",
    //"markdown.extension.editor.codeSpan.border": "#717cb450",
    //"markdown.extension.editor.formattingMark.foreground": "#a6accd40",
    //"markdown.extension.editor.trailingSpace.background": "#cccccc33",
    //"merge.commonContentBackground": "#60606029",
    //"merge.commonHeaderBackground": "#60606066",
    //"merge.currentContentBackground": "#40c8ae33",
    //"merge.currentHeaderBackground": "#40c8ae80",
    //"merge.incomingContentBackground": "#40a6ff33",
    //"merge.incomingHeaderBackground": "#40a6ff80",
    //"mergeEditor.change.background": "#9bb95533",
    //"mergeEditor.change.word.background": "#9ccc2c33",
    //"mergeEditor.changeBase.background": "#4b1818",
    //"mergeEditor.changeBase.word.background": "#6f1313",
    //"mergeEditor.conflict.handled.minimapOverViewRuler": "#adaca8ee",
    //"mergeEditor.conflict.handledFocused.border": "#c1c1c1cc",
    //"mergeEditor.conflict.handledUnfocused.border": "#86868649",
    //"mergeEditor.conflict.input1.background": "#40c8ae33",
    //"mergeEditor.conflict.input2.background": "#40a6ff33",
    //"mergeEditor.conflict.unhandled.minimapOverViewRuler": "#fcba03",
    //"mergeEditor.conflict.unhandledFocused.border": "#ffa600",
    //"mergeEditor.conflict.unhandledUnfocused.border": "#ffa6007a",
    //"mergeEditor.conflictingLines.background": "#ffea0047",
    //"minimap.errorHighlight": "#ff1212b3",
    //"minimap.findMatchHighlight": "#d18616",
    //"minimap.foregroundOpacity": "#000000",
    //"minimap.selectionHighlight": "#264f78",
    //"minimap.selectionOccurrenceHighlight": "#676767",
    //"minimap.warningHighlight": "#ffcb6b70",
    //"minimapGutter.addedBackground": "#c3e88d60",
    //"minimapGutter.deletedBackground": "#f0717860",
    //"minimapGutter.modifiedBackground": "#82aaff60",
    //"minimapSlider.activeBackground": "#80cbc480",
    //"minimapSlider.background": "#a6accd10",
    //"minimapSlider.hoverBackground": "#a6accd08",
    //"notebook.cellBorderColor": "#00000030",
    //"notebook.cellEditorBackground": "#1b1e2b",
    //"notebook.cellInsertionIndicator": "#ffffff00",
    //"notebook.cellStatusBarItemHoverBackground": "#ffffff26",
    //"notebook.cellToolbarSeparator": "#80808059",
    //"notebook.editorBackground": "#292d3e",
    //"notebook.focusedEditorBorder": "#ffffff00",
    //"notebook.selectedCellBackground": "#00000030",
    //"notebook.selectedCellBorder": "#00000030",
    //"notebook.symbolHighlightBackground": "#ffffff0b",
    //"notebookEditorOverviewRuler.runningCellForeground": "#89d185",
    //"notebookScrollbarSlider.activeBackground": "#80cbc4",
    //"notebookScrollbarSlider.background": "#a6accd20",
    //"notebookScrollbarSlider.hoverBackground": "#a6accd10",
    //"notebookStatusErrorIcon.foreground": "#f48771",
    //"notebookStatusRunningIcon.foreground": "#a6accd",
    //"notebookStatusSuccessIcon.foreground": "#89d185",
    //"notificationCenterHeader.background": "#353a51",
    //"notifications.border": "#353a51",
    //"notificationsErrorIcon.foreground": "#f0717870",
    //"notificationsInfoIcon.foreground": "#82aaff70",
    //"notificationsWarningIcon.foreground": "#ffcb6b70",
    //"panel.dropBorder": "#ffffff",
    //"panelInput.border": "#ffffff10",
    //"panelSection.border": "#00000060",
    //"panelSection.dropBackground": "#f0717880",
    //"panelSectionHeader.background": "#80808033",
    //"peekViewEditorStickyScroll.background": "#a6accd05",
    //"peekViewResult.fileForeground": "#ffffff",
    //"peekViewResult.lineForeground": "#bbbbbb",
    //"peekViewResult.selectionForeground": "#ffffff",
    //"peekViewTitleLabel.foreground": "#ffffff",
    //"ports.iconRunningProcessForeground": "#80cbc4",
    //"problemsErrorIcon.foreground": "#f0717870",
    //"problemsInfoIcon.foreground": "#82aaff70",
    //"problemsWarningIcon.foreground": "#ffcb6b70",
    //"profileBadge.background": "#4d4d4d",
    //"profileBadge.foreground": "#ffffff",
    //"quickInputList.focusBackground": "#a6accd20",
    //"quickInputList.focusForeground": "#80cbc4",
    //"quickInputTitle.background": "#ffffff1b",
    //"sash.hoverBorder": "#ffffff00",
    //"scm.providerBorder": "#454545",
    //"search.resultsInfoForeground": "#a6accda6",
    //"searchEditor.findMatchBackground": "#00000035",
    //"searchEditor.findMatchBorder": "#ffffff35",
    //"searchEditor.textInputBorder": "#ffffff10",
    //"settings.checkboxBorder": "#ffffff10",
    //"settings.dropdownBorder": "#ffffff10",
    //"settings.dropdownListBorder": "#80cbc4",
    //"settings.focusedRowBackground": "#1b1e2b99",
    //"settings.focusedRowBorder": "#ffffff00",
    //"settings.headerBorder": "#00000060",
    //"settings.numberInputBorder": "#ffffff10",
    //"settings.rowHoverBackground": "#1b1e2b4d",
    //"settings.sashBorder": "#00000060",
    //"settings.settingsHeaderHoverForeground": "#80cbc4b3",
    //"settings.textInputBorder": "#ffffff10",
    //"sideBar.dropBackground": "#f0717880",
    //"sideBarSectionHeader.foreground": "#757ca1",
    //"sideBySideEditor.horizontalBorder": "#00000030",
    //"sideBySideEditor.verticalBorder": "#00000030",
    //"statusBar.debuggingBorder": "#00000060",
    //"statusBar.focusBorder": "#676e95",
    //"statusBar.noFolderBorder": "#00000060",
    //"statusBar.noFolderForeground": "#676e95",
    //"statusBarItem.compactHoverBackground": "#ffffff33",
    //"statusBarItem.errorBackground": "#c72e0f",
    //"statusBarItem.errorForeground": "#ffffff",
    //"statusBarItem.focusBorder": "#676e95",
    //"statusBarItem.prominentBackground": "#00000080",
    //"statusBarItem.prominentForeground": "#676e95",
    //"statusBarItem.prominentHoverBackground": "#0000004d",
    //"statusBarItem.warningBackground": "#d98d0070",
    //"statusBarItem.warningForeground": "#ffffff",
    //"symbolIcon.arrayForeground": "#a6accd",
    //"symbolIcon.booleanForeground": "#a6accd",
    //"symbolIcon.classForeground": "#ee9d28",
    //"symbolIcon.colorForeground": "#a6accd",
    //"symbolIcon.constantForeground": "#a6accd",
    //"symbolIcon.constructorForeground": "#b180d7",
    //"symbolIcon.enumeratorForeground": "#ee9d28",
    //"symbolIcon.enumeratorMemberForeground": "#75beff",
    //"symbolIcon.eventForeground": "#ee9d28",
    //"symbolIcon.fieldForeground": "#75beff",
    //"symbolIcon.fileForeground": "#a6accd",
    //"symbolIcon.folderForeground": "#a6accd",
    //"symbolIcon.functionForeground": "#b180d7",
    //"symbolIcon.interfaceForeground": "#75beff",
    //"symbolIcon.keyForeground": "#a6accd",
    //"symbolIcon.keywordForeground": "#a6accd",
    //"symbolIcon.methodForeground": "#b180d7",
    //"symbolIcon.moduleForeground": "#a6accd",
    //"symbolIcon.namespaceForeground": "#a6accd",
    //"symbolIcon.nullForeground": "#a6accd",
    //"symbolIcon.numberForeground": "#a6accd",
    //"symbolIcon.objectForeground": "#a6accd",
    //"symbolIcon.operatorForeground": "#a6accd",
    //"symbolIcon.packageForeground": "#a6accd",
    //"symbolIcon.propertyForeground": "#a6accd",
    //"symbolIcon.referenceForeground": "#a6accd",
    //"symbolIcon.snippetForeground": "#a6accd",
    //"symbolIcon.stringForeground": "#a6accd",
    //"symbolIcon.structForeground": "#a6accd",
    //"symbolIcon.textForeground": "#a6accd",
    //"symbolIcon.typeParameterForeground": "#a6accd",
    //"symbolIcon.unitForeground": "#a6accd",
    //"symbolIcon.variableForeground": "#75beff",
    //"tab.lastPinnedBorder": "#4e5579",
    //"tab.unfocusedActiveBackground": "#292d3e",
    //"tab.unfocusedInactiveBackground": "#292d3e",
    //"tab.unfocusedInactiveForeground": "#757ca180",
    //"terminal.border": "#00000060",
    //"terminal.dropBackground": "#f0717880",
    //"terminal.findMatchBackground": "#000000",
    //"terminal.findMatchHighlightBackground": "#00000050",
    //"terminal.foreground": "#cccccc",
    //"terminal.hoverHighlightBackground": "#264f7820",
    //"terminal.inactiveSelectionBackground": "#717cb428",
    //"terminal.selectionBackground": "#717cb450",
    //"terminal.tab.activeBorder": "#80cbc4",
    //"terminalCommandDecoration.defaultBackground": "#ffffff40",
    //"terminalCommandDecoration.errorBackground": "#f14c4c",
    //"terminalCommandDecoration.successBackground": "#1b81a8",
    //"terminalOverviewRuler.cursorForeground": "#a0a0a0cc",
    //"terminalOverviewRuler.findMatchForeground": "#80cbc4",
    //"testing.iconErrored": "#f14c4c",
    //"testing.iconFailed": "#f14c4c",
    //"testing.iconPassed": "#73c991",
    //"testing.iconQueued": "#cca700",
    //"testing.iconSkipped": "#848484",
    //"testing.iconUnset": "#848484",
    //"testing.message.error.decorationForeground": "#f0717870",
    //"testing.message.error.lineBackground": "#ff000033",
    //"testing.message.info.decorationForeground": "#a6accd80",
    //"testing.peekBorder": "#f0717870",
    //"testing.peekHeaderBackground": "#f071780b",
    //"testing.runAction": "#73c991",
    //"textBlockQuote.background": "#7f7f7f1a",
    //"textBlockQuote.border": "#007acc80",
    //"textCodeBlock.background": "#0a0a0a66",
    //"textPreformat.foreground": "#d7ba7d",
    //"textSeparator.foreground": "#ffffff2e",
    //"toolbar.activeBackground": "#63666750",
    //"toolbar.hoverBackground": "#5a5d5e50",
    //"tree.inactiveIndentGuidesStroke": "#4e557966",
    //"tree.tableColumnsBorder": "#cccccc20",
    //"tree.tableOddRowsBackground": "#a6accd0a",
    //"walkThrough.embeddedEditorBackground": "#00000066",
    //"walkthrough.stepTitle.foreground": "#ffffff",
    //"welcomePage.progress.background": "#333747",
    //"welcomePage.progress.foreground": "#80cbc4",
    //"welcomePage.tileBackground": "#1b1e2b",
    //"welcomePage.tileBorder": "#ffffff1a",
    //"welcomePage.tileHoverBackground": "#202433",
    //"activityBar.activeBackground": null,
    //"activityBar.activeFocusBorder": null,
    //"button.border": null,
    //"contrastActiveBorder": null,
    //"contrastBorder": null,
    //"debugToolBar.border": null,
    //"diffEditor.border": null,
    //"diffEditor.insertedTextBorder": null,
    //"diffEditor.removedTextBorder": null,
    //"diffEditorGutter.insertedLineBackground": null,
    //"diffEditorGutter.removedLineBackground": null,
    //"diffEditorOverview.insertedForeground": null,
    //"diffEditorOverview.removedForeground": null,
    //"dropdown.listBackground": null,
    //"editor.findRangeHighlightBorder": null,
    //"editor.rangeHighlightBorder": null,
    //"editor.selectionForeground": null,
    //"editor.selectionHighlightBorder": null,
    //"editor.snippetFinalTabstopHighlightBackground": null,
    //"editor.snippetTabstopHighlightBorder": null,
    //"editor.symbolHighlightBorder": null,
    //"editor.wordHighlightBorder": null,
    //"editor.wordHighlightStrongBorder": null,
    //"editor.wordHighlightTextBorder": null,
    //"editorCursor.background": null,
    //"editorError.background": null,
    //"editorError.border": null,
    //"editorGhostText.background": null,
    //"editorGhostText.border": null,
    //"editorGroup.dropIntoPromptBorder": null,
    //"editorGroup.emptyBackground": null,
    //"editorGroupHeader.border": null,
    //"editorGroupHeader.tabsBorder": null,
    //"editorHint.border": null,
    //"editorInfo.background": null,
    //"editorInfo.border": null,
    //"editorLineNumber.dimmedForeground": null,
    //"editorOverviewRuler.background": null,
    //"editorSuggestWidget.selectedIconForeground": null,
    //"editorUnnecessaryCode.border": null,
    //"editorWarning.background": null,
    //"editorWarning.border": null,
    //"inputValidation.errorForeground": null,
    //"inputValidation.infoForeground": null,
    //"inputValidation.warningForeground": null,
    //"list.activeSelectionIconForeground": null,
    //"list.focusAndSelectionOutline": null,
    //"list.inactiveFocusBackground": null,
    //"list.inactiveFocusOutline": null,
    //"list.inactiveSelectionIconForeground": null,
    //"menu.border": null,
    //"merge.border": null,
    //"minimap.background": null,
    //"notebook.cellHoverBackground": null,
    //"notebook.focusedCellBackground": null,
    //"notebook.inactiveSelectedCellBorder": null,
    //"notebook.outputContainerBackgroundColor": null,
    //"notebook.outputContainerBorderColor": null,
    //"notificationCenter.border": null,
    //"notificationCenterHeader.foreground": null,
    //"notificationToast.border": null,
    //"panelSectionHeader.border": null,
    //"panelSectionHeader.foreground": null,
    //"peekViewEditor.matchHighlightBorder": null,
    //"quickInputList.focusIconForeground": null,
    //"tab.activeBorderTop": null,
    //"tab.hoverBackground": null,
    //"tab.hoverBorder": null,
    //"tab.hoverForeground": null,
    //"tab.unfocusedActiveBorderTop": null,
    //"tab.unfocusedHoverBackground": null,
    //"tab.unfocusedHoverBorder": null,
    //"tab.unfocusedHoverForeground": null,
    //"terminal.background": null,
    //"terminal.findMatchBorder": null,
    //"terminal.findMatchHighlightBorder": null,
    //"terminal.selectionForeground": null,
    //"testing.message.info.lineBackground": null,
    //"toolbar.hoverOutline": null,
    //"welcomePage.background": null,
    //"widget.border": null,
    //"window.activeBorder": null,
    //"window.inactiveBorder": null
  },
  tokenColors: [
    {
      scope: "string",
      settings: {
        foreground: "#C3E88D",
      },
    },
    {
      scope: "punctuation, constant.other.symbol",
      settings: {
        foreground: "#89DDFF",
      },
    },
    {
      scope:
        "constant.character.escape, text.html constant.character.entity.named",
      settings: {
        foreground: "#A6ACCD",
      },
    },
    {
      scope: "constant.language.boolean",
      settings: {
        foreground: "#FF9CAC",
      },
    },
    {
      scope: "constant.numeric",
      settings: {
        foreground: "#F78C6C",
      },
    },
    {
      scope:
        "variable, variable.parameter, support.variable, variable.language, support.constant, meta.definition.variable entity.name.function, meta.function-call.arguments",
      settings: {
        foreground: "#A6ACCD",
      },
    },
    {
      scope: "keyword.other",
      settings: {
        foreground: "#F78C6C",
      },
    },
    {
      scope:
        "keyword, modifier, variable.language.this, support.type.object, constant.language",
      settings: {
        foreground: "#89DDFF",
      },
    },
    {
      scope: "entity.name.function, support.function",
      settings: {
        foreground: "#82AAFF",
      },
    },
    {
      scope: "storage.type, storage.modifier, storage.control",
      settings: {
        foreground: "#C792EA",
      },
    },
    {
      scope: "support.module, support.node",
      settings: {
        foreground: "#F07178",
        fontStyle: "italic",
      },
    },
    {
      scope: "support.type, constant.other.key",
      settings: {
        foreground: "#FFCB6B",
      },
    },
    {
      scope: "entity.name.type, entity.other.inherited-class, entity.other",
      settings: {
        foreground: "#FFCB6B",
      },
    },
    {
      scope: "comment",
      settings: {
        foreground: "#676E95",
        fontStyle: "italic",
      },
    },
    {
      scope: "comment punctuation.definition.comment, string.quoted.docstring",
      settings: {
        foreground: "#676E95",
        fontStyle: "italic",
      },
    },
    {
      scope: "punctuation",
      settings: {
        foreground: "#89DDFF",
      },
    },
    {
      scope:
        "entity.name, entity.name.type.class, support.type, support.class, meta.use",
      settings: {
        foreground: "#FFCB6B",
      },
    },
    {
      scope:
        "variable.object.property, meta.field.declaration entity.name.function",
      settings: {
        foreground: "#F07178",
      },
    },
    {
      scope: "meta.definition.method entity.name.function",
      settings: {
        foreground: "#F07178",
      },
    },
    {
      scope: "meta.function entity.name.function",
      settings: {
        foreground: "#82AAFF",
      },
    },
    {
      scope:
        "template.expression.begin, template.expression.end, punctuation.definition.template-expression.begin, punctuation.definition.template-expression.end",
      settings: {
        foreground: "#89DDFF",
      },
    },
    {
      scope: "meta.embedded, source.groovy.embedded, meta.template.expression",
      settings: {
        foreground: "#A6ACCD",
      },
    },
    {
      scope: "entity.name.tag.yaml",
      settings: {
        foreground: "#F07178",
      },
    },
    {
      scope:
        "meta.object-literal.key, meta.object-literal.key string, support.type.property-name.json",
      settings: {
        foreground: "#F07178",
      },
    },
    {
      scope: "constant.language.json",
      settings: {
        foreground: "#89DDFF",
      },
    },
    {
      scope: "entity.other.attribute-name.class",
      settings: {
        foreground: "#FFCB6B",
      },
    },
    {
      scope: "entity.other.attribute-name.id",
      settings: {
        foreground: "#F78C6C",
      },
    },
    {
      scope: "source.css entity.name.tag",
      settings: {
        foreground: "#FFCB6B",
      },
    },
    {
      scope: "support.type.property-name.css",
      settings: {
        foreground: "#B2CCD6",
      },
    },
    {
      scope: "meta.tag, punctuation.definition.tag",
      settings: {
        foreground: "#89DDFF",
      },
    },
    {
      scope: "entity.name.tag",
      settings: {
        foreground: "#F07178",
      },
    },
    {
      scope: "entity.other.attribute-name",
      settings: {
        foreground: "#C792EA",
      },
    },
    {
      scope: "punctuation.definition.entity.html",
      settings: {
        foreground: "#A6ACCD",
      },
    },
    {
      scope: "markup.heading",
      settings: {
        foreground: "#89DDFF",
      },
    },
    {
      scope: "text.html.markdown meta.link.inline, meta.link.reference",
      settings: {
        foreground: "#F07178",
      },
    },
    {
      scope: "text.html.markdown beginning.punctuation.definition.list",
      settings: {
        foreground: "#89DDFF",
      },
    },
    {
      scope: "markup.italic",
      settings: {
        foreground: "#F07178",
        fontStyle: "italic",
      },
    },
    {
      scope: "markup.bold",
      settings: {
        foreground: "#F07178",
        fontStyle: "bold",
      },
    },
    {
      scope: "markup.bold markup.italic, markup.italic markup.bold",
      settings: {
        foreground: "#F07178",
        fontStyle: "italic bold",
      },
    },
    {
      scope:
        "markup.fenced_code.block.markdown punctuation.definition.markdown",
      settings: {
        foreground: "#C3E88D",
      },
    },
    {
      scope: "markup.inline.raw.string.markdown",
      settings: {
        foreground: "#C3E88D",
      },
    },
    {
      scope: "keyword.other.definition.ini",
      settings: {
        foreground: "#F07178",
      },
    },
    {
      scope: "entity.name.section.group-title.ini",
      settings: {
        foreground: "#89DDFF",
      },
    },
    {
      scope: "source.cs meta.class.identifier storage.type",
      settings: {
        foreground: "#FFCB6B",
      },
    },
    {
      scope: "source.cs meta.method.identifier entity.name.function",
      settings: {
        foreground: "#F07178",
      },
    },
    {
      scope:
        "source.cs meta.method-call meta.method, source.cs entity.name.function",
      settings: {
        foreground: "#82AAFF",
      },
    },
    {
      scope: "source.cs storage.type",
      settings: {
        foreground: "#FFCB6B",
      },
    },
    {
      scope: "source.cs meta.method.return-type",
      settings: {
        foreground: "#FFCB6B",
      },
    },
    {
      scope: "source.cs meta.preprocessor",
      settings: {
        foreground: "#676E95",
      },
    },
    {
      scope: "source.cs entity.name.type.namespace",
      settings: {
        foreground: "#A6ACCD",
      },
    },
    {
      scope: "meta.jsx.children, SXNested",
      settings: {
        foreground: "#A6ACCD",
      },
    },
    {
      scope: "support.class.component",
      settings: {
        foreground: "#FFCB6B",
      },
    },
    {
      scope: "source.cpp meta.block variable.other",
      settings: {
        foreground: "#A6ACCD",
      },
    },
    {
      scope: "source.python meta.member.access.python",
      settings: {
        foreground: "#F07178",
      },
    },
    {
      scope:
        "source.python meta.function-call.python, meta.function-call.arguments",
      settings: {
        foreground: "#82AAFF",
      },
    },
    {
      scope: "meta.block",
      settings: {
        foreground: "#F07178",
      },
    },
    {
      scope: "entity.name.function.call",
      settings: {
        foreground: "#82AAFF",
      },
    },
    {
      scope:
        "source.php support.other.namespace, source.php meta.use support.class",
      settings: {
        foreground: "#A6ACCD",
      },
    },
    {
      scope: "constant.keyword",
      settings: {
        foreground: "#89DDFF",
        fontStyle: "italic",
      },
    },
    {
      scope: "entity.name.function",
      settings: {
        foreground: "#82AAFF",
      },
    },
    {
      scope: ["markup.deleted"],
      settings: {
        foreground: "#F07178",
      },
    },
    {
      scope: ["markup.inserted"],
      settings: {
        foreground: "#C3E88D",
      },
    },
    {
      scope: ["markup.underline"],
      settings: {
        fontStyle: "underline",
      },
    },
    {
      scope: ["keyword.control"],
      settings: {
        foreground: "#89DDFF",
        fontStyle: "italic",
      },
    },
    {
      scope: ["variable.parameter"],
      settings: {
        fontStyle: "italic",
      },
    },
    {
      scope: ["variable.parameter.function.language.special.self.python"],
      settings: {
        foreground: "#F07178",
        fontStyle: "italic",
      },
    },
    {
      scope: ["constant.character.format.placeholder.other.python"],
      settings: {
        foreground: "#F78C6C",
      },
    },
    {
      scope: ["markup.quote"],
      settings: {
        foreground: "#89DDFF",
        fontStyle: "italic",
      },
    },
    {
      scope: ["markup.fenced_code.block"],
      settings: {
        foreground: "#A6ACCD90",
      },
    },
    {
      scope: ["punctuation.definition.quote"],
      settings: {
        foreground: "#FF9CAC",
      },
    },
    {
      scope: ["meta.structure.dictionary.json support.type.property-name.json"],
      settings: {
        foreground: "#C792EA",
      },
    },
    {
      scope: [
        "meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
      ],
      settings: {
        foreground: "#FFCB6B",
      },
    },
    {
      scope: [
        "meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
      ],
      settings: {
        foreground: "#F78C6C",
      },
    },
    {
      scope: [
        "meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
      ],
      settings: {
        foreground: "#F07178",
      },
    },
    {
      scope: [
        "meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
      ],
      settings: {
        foreground: "#916B53",
      },
    },
    {
      scope: [
        "meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
      ],
      settings: {
        foreground: "#82AAFF",
      },
    },
    {
      scope: [
        "meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
      ],
      settings: {
        foreground: "#FF9CAC",
      },
    },
    {
      scope: [
        "meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
      ],
      settings: {
        foreground: "#C792EA",
      },
    },
    {
      scope: [
        "meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
      ],
      settings: {
        foreground: "#C3E88D",
      },
    },
    {
      scope: "token.info-token",
      settings: {
        foreground: "#6796E6",
      },
    },
    {
      scope: "token.warn-token",
      settings: {
        foreground: "#CD9731",
      },
    },
    {
      scope: "token.error-token",
      settings: {
        foreground: "#F44747",
      },
    },
    {
      scope: "token.debug-token",
      settings: {
        foreground: "#B267E6",
      },
    },
  ],
};
const t = convertTheme(theme);

fs.writeFileSync(
  "./src/component/codeEditor/monacoTheme.ts",
  JSON.stringify(t, null, 2)
);

/*
 * Convert multiple vscode themes to monaco themes.
 * This function takes as arguments an input directory with generated vscode json files and generated output files with the same names at output directory.
 */
// convertThemeFromDir('./my-vscode-themes-collection-dir/in','./my-vscode-themes-collection-dir/out');
